name: census
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytest
  - scikit-learn
  - pandas
  - notebook
  - jupyterlab
  - fastapi
  - uvicorn
  - dvc
  - dvc-gdrive
  - imbalanced-learn
  pip:
    - "uvicorn[standard]"

